version: "3"
services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    expose:
      - 1521
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: Oradoc_db1
      ORACLE_SID: xe
      DB_SID: "xe"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local
