spring:
  application:
    name: cbmes-audit
  sleuth:
    sampler:
      probability: 0.1
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: admin_user
    password: Oradoc_db1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
