spring:
  application:
    name: audit-app
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: admin_user
    password: Oradoc_db1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html